In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Data points
X = np.array([1, 2, 3, 4, 5])
Y = np.array([1.2, 2.8, 3.6, 4.5, 5.1])
# Stack the design matrix with a column of ones (for the intercept)
A = np.vstack([X, np.ones(len(X))]).T

print("X:")
print(X)

print("Y:")
print(Y)

print("A:")
print(A)

X:
[1 2 3 4 5]
Y:
[1.2 2.8 3.6 4.5 5.1]
A:
[[1. 1.]
 [2. 1.]
 [3. 1.]
 [4. 1.]
 [5. 1.]]


In [4]:
# Solve using least squares
m, c = np.linalg.lstsq(A, Y, rcond=None)[0]
print(f"Slope: {m}, Intercept: {c}")

Slope: 0.9500000000000001, Intercept: 0.5900000000000001
