In [1]:
import numpy as np

Gaussian Elimination:

In [20]:
def gaussian_elimination(A, b):
    n = len(b)
    # Forward elimination
    for i in range(n):
        # Pivoting
        max_row = max(range(i, n), key=lambda x: abs(A[x][i]))
        A[i], A[max_row] = A[max_row], A[i]
        b[i], b[max_row] = b[max_row], b[i]
        
        # Make the rows below this one 0 in current column
        for j in range(i + 1, n):
            ratio = A[j][i] / A[i][i]
            A[j] = [A[j][k] - ratio * A[i][k] for k in range(n)]
            b[j] -= ratio * b[i]
    
    # Backward substitution
    x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - sum(A[i][j] * x[j] for j in range(i + 1, n))) / A[i][i]
    
    return x

In [21]:
A = [[3, 2, -4], [2, 3, 3], [5, -3, 1]]
b = [3, 15, 14]
solution = gaussian_elimination(A, b)
print(f"Solution: {solution}")

Solution: [2.9999999999999996, 0.9999999999999996, 2.0]


In [22]:
sol = np.linalg.solve(A, b)
print(sol)

[3. 1. 2.]


LU Decomposition:

In [23]:
def lu_decomposition(A):
    n = len(A)
    L = np.eye(n)  # Initialize L as an identity matrix
    U = np.array(A, dtype=float)  # Copy of A to avoid
    # modifying the original matrix
        # modifying the original matrix
    
    for i in range(n):
        # Eliminate elements below the pivot (U[i, i])
        for j in range(i+1, n):
            if U[i, i] == 0:
                raise ValueError("Zero pivot encountered. LU decomposition cannot proceed.")
            
            factor = U[j, i] / U[i, i]  # Multiplier for row
     # operation
            L[j, i] = factor  # Store multiplier in L
            
            # Update the rows of U
            for k in range(i, n):
                U[j, k] -= factor * U[i, k]
    
    return L, U

In [24]:
B = [[2, 3, 1], 
     [4, 7, -1], 
     [-2, 1, 2]]
L, U = lu_decomposition(B)
print("Matrix B:\n", B)
print("Lower Triangular Matrix:\n", L)
print("Upper Triangular Matrix:\n", U)

Matrix B:
 [[2, 3, 1], [4, 7, -1], [-2, 1, 2]]
Lower Triangular Matrix:
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  4.  1.]]
Upper Triangular Matrix:
 [[ 2.  3.  1.]
 [ 0.  1. -3.]
 [ 0.  0. 15.]]


In [25]:
print(L@U)

[[ 2.  3.  1.]
 [ 4.  7. -1.]
 [-2.  1.  2.]]
